from manimlib.imports import *

# this video is on www.bilibili.com/video/BV1BK41177QH now



# HCl Ba(NO3)2 KCl Na2CO3
class test(Scene):
    def construct(self):
        cup_path = 'E:/manim_install/manim-master/my_svg/chemistry/cup/cup.svg'
        liquid_path = 'E:/manim_install/manim-master/my_svg/chemistry/cup/liquid_high.svg'
        cup1 = SVGMobject()
        cup1.set_fill(opacity=0)
        cup1_water = SVGMobject(liquid_path)
        cup1_water.set_color(WHITE)
        cup1_water.set_fill(WHITE, opacity=0.8)
        cup1_water.set_plot_depth(-1)
        text1 = TexMobject('\\ce{HCl}')
        text1.move_to(LEFT*3+UP*2)
        text1.set_fill(BLUE)

        cup2 = SVGMobject(cup_path)
        cup2.set_fill(opacity=0)
        cup2.scale(0.6)
        cup2.shift(LEFT)
        cup2_water = SVGMobject(liquid_path)
        cup2_water.set_color(WHITE)
        cup2_water.set_fill(WHITE, opacity=0.8)
        cup2_water.set_plot_depth(-1)
        cup2_water.shift(LEFT)
        cup2_water.scale(0.6)
        text2 = TexMobject('\\ce{Ba(NO3)2}')
        text2.move_to(LEFT+UP*2)
        text2.set_fill(BLUE)

        cup3 = SVGMobject(cup_path)
        cup3.set_fill(opacity=0)
        cup3.scale(0.6)
        cup3_water = SVGMobject(liquid_path)
        cup3_water.set_color(WHITE)
        cup3_water.set_fill(WHITE, opacity=0.8)
        cup3_water.set_plot_depth(-1)
        cup3.shift(RIGHT)
        cup3_water.shift(RIGHT)
        cup3_water.scale(0.6)
        text3 = TexMobject('\\ce{KCl}')
        text3.move_to(RIGHT+UP*2)
        text3.set_fill(BLUE)

        cup4 = SVGMobject(cup_path)
        cup4.set_fill(opacity=0)
        cup4.scale(0.6)
        cup4_water = SVGMobject(liquid_path)
        cup4_water.set_color(WHITE)
        cup4_water.set_fill(WHITE, opacity=0.8)
        cup4_water.set_plot_depth(-1)
        cup4.shift(RIGHT*3)
        cup4_water.shift(RIGHT*3)
        cup4_water.scale(0.6)
        text4 = TexMobject('\\ce{Na2CO3}')
        text4.move_to(RIGHT*3+UP*2)
        text4.set_fill(BLUE)

        self.play(FadeInFromLarge(cup1), FadeInFromLarge(cup1_water))
        self.wait(1)
        self.play(cup1.shift, LEFT*3, cup1.scale, 0.6, cup1_water.scale, 0.6, cup1_water.shift, LEFT*3, FadeInFromLeft(cup2), FadeInFromLeft(cup2_water), FadeInFromLeft(cup3), FadeInFromLeft(cup3_water), FadeInFromLeft(cup4), FadeInFromLeft(cup4_water))
        group_cups = Group(cup1, cup2, cup3, cup4, cup1_water, cup2_water, cup3_water, cup4_water)
        self.wait(0.5)
        self.play(group_cups.shift, UP*3)
        xx_group = Group(text1, text2, text3, text4, )
        self.play(ShowCreation(xx_group), )
        self.wait(1.5)
        self.play(FadeOut(xx_group))
        self.wait(1.8)
        self.play(FadeIn(xx_group))
        self.wait(2.5)


        text1_2 = TexMobject('\\ce{HCl}')
        text1_2.move_to(LEFT*2+DOWN)

        text2_2 = TexMobject('\\ce{Ba(NO3)2}')
        text2_2.shift(RIGHT)
        text3_2 = TexMobject('\\ce{KCl}')
        text3_2.shift(RIGHT+DOWN)
        text4_2 = TexMobject('\\ce{Na2CO3}')
        text4_2.shift(RIGHT+DOWN*2)
        self.play(TransformFromCopy(text1, text1_2))
        self.wait(2)
        self.play(FadeIn(text2_2), FadeIn(text3_2), FadeIn(text4_2))
        self.wait(1)

        arrow1 = Arrow(LEFT*1.5+DOWN, UP*0.2)
        arrow2 = Arrow(LEFT*1.5+DOWN, DOWN+RIGHT*0.7)
        arrow3 = Arrow(LEFT*1.5+DOWN, DOWN*2.2)
        self.play(ShowCreation(arrow1), run_time=0.2)
        self.play(ShowCreation(arrow2), run_time=0.2)
        self.play(ShowCreation(arrow3), run_time=0.2)
        self.wait(4)

        down_arrow = TextMobject('\\ce{ ^ }')
        down_arrow.set_color(RED)
        down_arrow.scale(1.3)
        down_arrow.move_to(text4_2.get_center()+RIGHT*1.5)
        self.play(Write(down_arrow))
        self.wait(1.5)
        down_arrow_cpoy1 = down_arrow.copy()

        self.play(down_arrow_cpoy1.move_to, text1_2.get_center()+LEFT*0.8)
        down_arrow_cpoy2 = down_arrow_cpoy1.copy()
        self.wait(1)
        self.play(down_arrow_cpoy2.move_to, text1.get_center()+DOWN*0.8)
        self.wait(2)
        self.play(FadeOutAndShift(down_arrow_cpoy1), FadeOutAndShift(down_arrow), FadeOutAndShift(arrow1), FadeOutAndShift(arrow2), FadeOutAndShift(arrow3), FadeOutAndShift(text1_2), FadeOutAndShift(text2_2), FadeOutAndShift(text3_2), FadeOutAndShift(text4_2))
        self.wait(3)

        xx_2 = TextMobject('\\ce{ v }')
        xx_2.move_to(text2.get_center()+DOWN*0.8)
        xx_2.set_color(RED)
        xx_2.scale(1.3)
        xx_3 = TextMobject('Nothing')
        xx_3.move_to(text3.get_center()+DOWN*0.8)
        xx_3.set_color(RED)
        xx_3.scale(1.3)
        xx_4 = TextMobject('\\ce{ ^ v }')
        xx_4.move_to(text4.get_center() + DOWN * 0.8)
        xx_4.set_color(RED)
        xx_4.scale(1.3)
        self.play(ShowCreation(xx_2), ShowCreation(xx_3), ShowCreation(xx_4))
        self.wait(3)


        kuohao = Brace(Group(down_arrow_cpoy2, xx_4))
        different_text = TextMobject('Different from each other')
        different_text.move_to(kuohao.get_center()+DOWN*0.5)
        self.play(ShowCreation(kuohao), Write(different_text), run_time=1.5)
        self.wait(8)

        middle_group = Group(kuohao, different_text)

        xx_1_copy = down_arrow_cpoy2.copy().shift(DOWN*4.5+RIGHT*4)
        xx_2_copy = xx_2.copy().shift(DOWN*4.5+LEFT*2)
        xx_3_copy = xx_3.copy().shift(DOWN*4.5+RIGHT*2)
        xx_4_copy = xx_4.copy().shift(DOWN*4.5+LEFT*4)

        group_cups_copy = group_cups.copy()
        group_cups_copy.shift(DOWN*5)

        connect_1 = Arrow(LEFT*3+DOWN*1.2, LEFT+UP*1)
        connect_2 = Arrow(LEFT+DOWN*1.2, RIGHT*3+UP*1)
        connect_3 = Arrow(RIGHT+DOWN*1.2, LEFT*3+UP*1)
        connect_4 = Arrow(RIGHT*3+DOWN*1.2, RIGHT+UP*1)


        self.play(FadeIn(group_cups_copy), FadeOut(middle_group))
        self.wait(1.5)
        self.play(FadeIn(xx_1_copy), FadeIn(xx_2_copy), FadeIn(xx_3_copy), FadeIn(xx_4_copy), )
        self.wait(2.5)
        group_cups_copy.add(xx_1_copy, xx_2_copy, xx_3_copy, xx_4_copy, )
        self.play(ShowCreation(connect_1), run_time=0.2)
        self.play(ShowCreation(connect_2), run_time=0.2)
        self.play(ShowCreation(connect_3), run_time=0.2)
        self.play(ShowCreation(connect_4), run_time=0.2)
        self.wait(3)

        self.play(FadeOut(connect_1), FadeOut(connect_2), FadeOut(connect_3), FadeOut(connect_4), FadeOut(down_arrow_cpoy2), FadeOut(xx_2), FadeOut(xx_3), FadeOut(xx_4), FadeOut(group_cups_copy), FadeOut(xx_1_copy), FadeOut(xx_2_copy), FadeOut(xx_3_copy), FadeOut(xx_4_copy),)
        self.wait(3.5)

        group_hcl = Group(text1, cup1, cup1_water)
        group_ba = Group(text2, cup2, cup2_water)
        group_kcl = Group(text3, cup3, cup3_water)
        group_na = Group(text4, cup4, cup4_water)

        self.play(FadeOut(group_ba), FadeOut(group_kcl), FadeOut(group_na), )
        self.play(group_hcl.shift, LEFT)
        self.wait(1)

        hcl_ba = TextMobject('\\ce{HCl + Ba(NO3)2 = }Nothing').shift(UP)
        hcl_kcl = TextMobject('\\ce{HCl + KCl = }Nothing')
        hcl_na = TextMobject('\\ce{2HCl + Na2CO3 = 2NaCl + CO2 ^ + H2O}').shift(DOWN)

        down_arrow_cpoy2.move_to(group_hcl.get_center()+DOWN*1.8)
        self.play(Write(hcl_ba), Write(hcl_kcl), Write(hcl_na), )
        self.wait(3.5)
        self.play(hcl_na.set_color, YELLOW)
        self.wait(1.5)
        self.play(Transform(hcl_na, down_arrow_cpoy2), FadeOut(hcl_ba), FadeOut(hcl_kcl))
        self.wait(1)
        group_hcl.add(down_arrow_cpoy2)
        hcl_na.move_to(UP*10)
        self.play(group_hcl.shift, RIGHT)
        self.wait(0.8)
        self.play(FadeOut(group_hcl), FadeIn(group_ba))
        self.wait(0.8)
        self.play(group_ba.shift, LEFT*3)
        self.wait(2)

        ba_hcl = TextMobject('\\ce{Ba(NO3)2 + HCl = }Nothing').shift(UP)
        ba_kcl = TextMobject('\\ce{Ba(NO3)2 + KCl = }Nothing')
        ba_na = TextMobject('\\ce{Ba(NO3)2 + Na2CO3 = BaCO3 v + 2NaNO3}').shift(DOWN)

        xx_2.move_to(group_ba.get_center()+DOWN*1.8)
        self.play(Write(ba_hcl), Write(ba_kcl), Write(ba_na), )
        self.wait(3.5)
        self.play(ba_na.set_color, YELLOW)
        self.wait(1.5)
        self.play(Transform(ba_na, xx_2), FadeOut(ba_hcl), FadeOut(ba_kcl))
        self.wait(1)
        group_ba.add(xx_2)
        ba_na.move_to(UP*10)
        self.play(group_ba.shift, RIGHT*3,)
        self.wait(0.8)
        self.play(FadeOut(group_ba), FadeIn(group_kcl))
        self.wait(0.8)
        self.play(group_kcl.shift, LEFT*5)
        self.wait(2)

        kcl_hcl = TextMobject('\\ce{KCl + HCl = }Nothing').shift(UP)
        kcl_ba = TextMobject('\\ce{KCl + Ba(NO3)2 = }Nothing')
        kcl_na = TextMobject('\\ce{KCl + Na2CO3 = }Nothing').shift(DOWN)
        group_nothing = Group(kcl_hcl, kcl_ba, kcl_na)
        noting_rec = Rectangle().surround(group_nothing)
        noting_rec.set_color(RED)
        noting_rec.set_fill(opacity=0)

        xx_3.move_to(group_kcl.get_center() + DOWN * 1.8)
        self.play(Write(kcl_ba), Write(kcl_hcl), Write(kcl_na), )
        self.wait(3.5)
        self.play(ShowCreationThenDestruction(noting_rec))
        self.wait(2)
        self.play(Transform(group_nothing, xx_3))
        self.wait(1.5)
        group_nothing.shift(UP * 10)
        group_kcl.add(xx_3)
        self.play(group_kcl.shift, RIGHT * 5)
        self.wait(0.8)
        self.play(FadeOut(group_kcl), FadeIn(group_na))
        self.wait(0.8)
        self.play(group_na.shift, LEFT * 7)
        self.wait(1)

        na_hcl = TextMobject('\\ce{Na2CO3 + 2HCl = 2NaCl + CO2 ^ + H2O}').shift(UP)
        na_ba = TextMobject('\\ce{Na2CO3 + Ba(NO3)2 = BaCO3 v + 2NaNO3}')
        na_kcl = TextMobject('\\ce{Na2CO3 + KCl = }Nothing').shift(DOWN)


        xx_4.move_to(group_na.get_center()+DOWN*1.8)
        self.play(Write(na_hcl), Write(na_ba), Write(na_kcl), )
        self.wait(3.5)
        group_xx_4 = Group(na_hcl, na_ba)
        self.play(group_xx_4.set_color, YELLOW)
        self.wait(1.5)
        self.play(Transform(group_xx_4, xx_4), FadeOut(na_kcl))
        self.wait(1)
        group_xx_4.shift(UP*10)
        group_na.add(xx_4)
        self.play(group_na.shift, RIGHT*7)
        self.wait(0.8)
        self.play(FadeIn(group_hcl), FadeIn(group_ba), FadeIn(group_kcl))


        self.wait(3)
        group_final_all = Group(group_hcl, group_ba, group_kcl, group_na)
        text_BQ = TextMobject('BQ')
        text_BQ.set_color(BLUE)
        text_BQ.scale(3)
        self.play(Transform(group_final_all, text_BQ))
        self.wait(2)
        self.play(FadeOut(group_final_all))




        self.wait(3)

if __name__ == '__main__':
    os.system('python manim.py -p --high_quality chemistry_qufen_4.py test')
